# Generated by Django 5.2 on 2025-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='gallery_thumbnail/'),
        ),
    ]
