# Generated by Django 5.2 on 2025-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldepartment',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='departments/'),
        ),
    ]
